### ISSUE TITLE
Melpe stable

### ISSUE THREAD

**Issue by nlamirault** [echosa/emacsagist#1]
could you please create a tag to use this package using melpa stable [1].
Thanks

[1] : http://stable.melpa.org/

**Comment by echosa** [comment]
I don’t see anything on the stable melpa site to tell me how to do so. Am I just missing the instructions?

**Comment by echosa** [comment]
@nlamirault I've created a tag `1.0.0` for this package. If that's all I needed to do, please close this issue. If not, let me know what else you need from me. Thanks!

**Comment by nlamirault** [comment]
Thanks : http://stable.melpa.org/#/emacsagist
